FROM flowweaver:gocv-base

WORKDIR /FloWWeaver

COPY go.mod go.sum ./

RUN go mod download

COPY cmd ./cmd
COPY internal ./internal
COPY api ./api

RUN go build -o flowweaver_grpc ./cmd/grpc_app/main.go

CMD ["./flowweaver_grpc"]