// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.6.1
// source: RPCStructs.proto

package base_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fps           float32                `protobuf:"fixed32,2,opt,name=fps,proto3" json:"fps,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	StreamType    uint32                 `protobuf:"varint,5,opt,name=streamType,proto3" json:"streamType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewStream) Reset() {
	*x = NewStream{}
	mi := &file_RPCStructs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewStream) ProtoMessage() {}

func (x *NewStream) ProtoReflect() protoreflect.Message {
	mi := &file_RPCStructs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewStream.ProtoReflect.Descriptor instead.
func (*NewStream) Descriptor() ([]byte, []int) {
	return file_RPCStructs_proto_rawDescGZIP(), []int{0}
}

func (x *NewStream) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewStream) GetFps() float32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *NewStream) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *NewStream) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *NewStream) GetStreamType() uint32 {
	if x != nil {
		return x.StreamType
	}
	return 0
}

type RemoveStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStream) Reset() {
	*x = RemoveStream{}
	mi := &file_RPCStructs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStream) ProtoMessage() {}

func (x *RemoveStream) ProtoReflect() protoreflect.Message {
	mi := &file_RPCStructs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStream.ProtoReflect.Descriptor instead.
func (*RemoveStream) Descriptor() ([]byte, []int) {
	return file_RPCStructs_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveStream) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_RPCStructs_proto protoreflect.FileDescriptor

var file_RPCStructs_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x52, 0x50, 0x43, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x22, 0x7f, 0x0a, 0x09,
	0x4e, 0x65, 0x77, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x66, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x66, 0x70, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x22, 0x22, 0x0a,
	0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x6f, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x3b, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_RPCStructs_proto_rawDescOnce sync.Once
	file_RPCStructs_proto_rawDescData []byte
)

func file_RPCStructs_proto_rawDescGZIP() []byte {
	file_RPCStructs_proto_rawDescOnce.Do(func() {
		file_RPCStructs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RPCStructs_proto_rawDesc), len(file_RPCStructs_proto_rawDesc)))
	})
	return file_RPCStructs_proto_rawDescData
}

var file_RPCStructs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_RPCStructs_proto_goTypes = []any{
	(*NewStream)(nil),    // 0: base_rpc.NewStream
	(*RemoveStream)(nil), // 1: base_rpc.RemoveStream
}
var file_RPCStructs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RPCStructs_proto_init() }
func file_RPCStructs_proto_init() {
	if File_RPCStructs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RPCStructs_proto_rawDesc), len(file_RPCStructs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RPCStructs_proto_goTypes,
		DependencyIndexes: file_RPCStructs_proto_depIdxs,
		MessageInfos:      file_RPCStructs_proto_msgTypes,
	}.Build()
	File_RPCStructs_proto = out.File
	file_RPCStructs_proto_goTypes = nil
	file_RPCStructs_proto_depIdxs = nil
}
