// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/restream/": {
            "get": {
                "description": "Processes the presigned URL and starts the stream",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stream"
                ],
                "summary": "Process stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Encrypted stream configuration",
                        "name": "signature",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client_stream_creator.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/restream/presigned/": {
            "post": {
                "description": "Generates an encrypted presigned URL for creating a new stream",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stream"
                ],
                "summary": "Generate presigned URL",
                "parameters": [
                    {
                        "description": "Stream configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client_stream_creator.ClientNewStreamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client_stream_creator.PresignedURLResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client_stream_creator.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "client_stream_creator.ClientNewStreamRequest": {
            "type": "object",
            "properties": {
                "streamT": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "client_stream_creator.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "client_stream_creator.PresignedURLResponse": {
            "type": "object",
            "properties": {
                "presigned_url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Video Streamer API",
	Description:      "API for video streaming service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
